### ISSUE TITLE
你好我想知道TinkerPatch是否支持新建类和资源呢

### ISSUE THREAD

**Issue by wozhizhizhi** [TinkerPatch/tinkerpatch-sdk#24]
你好我想知道TinkerPatch是否支持新建类和资源呢

**Comment by shwenzhang** [comment]
支持

**Comment by wozhizhizhi** [comment]
额？文档好像说不支持新建Activity

**Comment by simpleton** [comment]
是的，所有需要更改manifest是不支持的。

On Feb 6, 2017 7:04 PM, "new cat" <notifications@github.com> wrote:

额？文档好像说不支持新建Activity

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/TinkerPatch/tinkerpatch-sdk/issues/24#issuecomment-277650778>,
or mute the thread
